# Generated by Django 4.1.3 on 2022-11-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="note", name="body",),
        migrations.AddField(
            model_name="note", name="api", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="note", name="massge", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="note", name="reply", field=models.TextField(null=True),
        ),
    ]
