# Generated by Django 4.1.3 on 2022-11-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_note_body_note_api_note_massge_note_reply"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note", old_name="massge", new_name="message",
        ),
    ]
