# Generated by Django 4.1.4 on 2023-02-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="audio",
            field=models.FileField(null=True, upload_to="note/"),
        ),
    ]
