# Generated by Django 4.1.4 on 2023-02-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_note_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="video", name="message", field=models.TextField(null=True),
        ),
    ]
